/**
 * Markdown Report Generator
 * Creates human-readable reports with findings summary and details
 */

import { Finding, ScanSummary, Severity, FindingCategory } from '../types';
import { groupByCategory, groupByPage } from '../utils/dedup';

export interface MarkdownReportOptions {
  includeScreenshots: boolean;
  includeEvidence: boolean;
  maxFindingsPerPage: number;
  groupBy: 'severity' | 'category' | 'page';
}

export function generateMarkdownReport(
  summary: ScanSummary,
  findings: Finding[],
  options: Partial<MarkdownReportOptions> = {}
): string {
  const opts: MarkdownReportOptions = {
    includeScreenshots: true,
    includeEvidence: true,
    maxFindingsPerPage: 50,
    groupBy: 'severity',
    ...options,
  };

  const sections: string[] = [];

  // Header
  sections.push('# UI Bug Scanner Report');
  sections.push('');
  sections.push(`**Scan Date:** ${summary.startTime}`);
  sections.push(`**Duration:** ${summary.scanDuration}`);
  sections.push(`**Pages Scanned:** ${summary.pagesScanned}`);
  sections.push(`**Viewports:** ${summary.viewportsScanned.join(', ')}`);
  sections.push('');

  // Summary statistics
  sections.push('## Summary');
  sections.push('');
  sections.push(generateSummaryTable(summary));
  sections.push('');

  // Category breakdown
  sections.push('### By Category');
  sections.push('');
  sections.push(generateCategoryTable(summary));
  sections.push('');

  // Errors section (if any)
  if (summary.errors.length > 0) {
    sections.push('## Scan Errors');
    sections.push('');
    sections.push('The following pages could not be scanned:');
    sections.push('');
    for (const error of summary.errors.slice(0, 10)) {
      sections.push(`- **${error.pageUrl}** (${error.viewport}): ${error.error}`);
    }
    if (summary.errors.length > 10) {
      sections.push(`- ... and ${summary.errors.length - 10} more errors`);
    }
    sections.push('');
  }

  // Findings
  sections.push('## Findings');
  sections.push('');

  if (findings.length === 0) {
    sections.push('✅ No issues found!');
  } else {
    switch (opts.groupBy) {
      case 'severity':
        sections.push(generateFindingsBySeverity(findings, opts));
        break;
      case 'category':
        sections.push(generateFindingsByCategory(findings, opts));
        break;
      case 'page':
        sections.push(generateFindingsByPage(findings, opts));
        break;
    }
  }

  // Footer
  sections.push('');
  sections.push('---');
  sections.push('');
  sections.push('*Generated by UI Bug Scanner Agent Skill*');
  sections.push('');
  sections.push('### References');
  sections.push('');
  sections.push('- [WCAG 2.1 Guidelines](https://www.w3.org/TR/WCAG21/)');
  sections.push('- [WCAG 2.2 Guidelines](https://www.w3.org/TR/WCAG22/)');
  sections.push('- [axe-core Rules](https://dequeuniversity.com/rules/axe/)');

  return sections.join('\n');
}

function generateSummaryTable(summary: ScanSummary): string {
  const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
  const emojis: Record<Severity, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  };

  const lines: string[] = [];
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');

  for (const severity of severities) {
    const count = summary.findings[severity] || 0;
    if (count > 0 || severity === 'critical' || severity === 'high') {
      lines.push(`| ${emojis[severity]} ${capitalizeFirst(severity)} | ${count} |`);
    }
  }

  const total = Object.values(summary.findings).reduce((a, b) => a + b, 0);
  lines.push(`| **Total** | **${total}** |`);

  return lines.join('\n');
}

function generateCategoryTable(summary: ScanSummary): string {
  const lines: string[] = [];
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');

  const categories: FindingCategory[] = ['accessibility', 'usability', 'spec'];
  for (const category of categories) {
    const count = summary.byCategory[category] || 0;
    lines.push(`| ${capitalizeFirst(category)} | ${count} |`);
  }

  return lines.join('\n');
}

function generateFindingsBySeverity(
  findings: Finding[],
  opts: MarkdownReportOptions
): string {
  const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
  const sections: string[] = [];

  for (const severity of severities) {
    const severityFindings = findings.filter((f) => f.severity === severity);
    if (severityFindings.length === 0) continue;

    sections.push(`### ${getSeverityEmoji(severity)} ${capitalizeFirst(severity)} (${severityFindings.length})`);
    sections.push('');

    for (const finding of severityFindings.slice(0, opts.maxFindingsPerPage)) {
      sections.push(formatFinding(finding, opts));
      sections.push('');
    }

    if (severityFindings.length > opts.maxFindingsPerPage) {
      sections.push(
        `*... and ${severityFindings.length - opts.maxFindingsPerPage} more ${severity} findings*`
      );
      sections.push('');
    }
  }

  return sections.join('\n');
}

function generateFindingsByCategory(
  findings: Finding[],
  opts: MarkdownReportOptions
): string {
  const sections: string[] = [];
  const grouped = groupByCategory(findings);

  const categoryIcons: Record<FindingCategory, string> = {
    accessibility: '♿',
    usability: '🖱️',
    spec: '📐',
  };

  for (const [category, categoryFindings] of grouped) {
    sections.push(
      `### ${categoryIcons[category as FindingCategory] || '📋'} ${capitalizeFirst(category)} (${categoryFindings.length})`
    );
    sections.push('');

    for (const finding of categoryFindings.slice(0, opts.maxFindingsPerPage)) {
      sections.push(formatFinding(finding, opts));
      sections.push('');
    }

    if (categoryFindings.length > opts.maxFindingsPerPage) {
      sections.push(
        `*... and ${categoryFindings.length - opts.maxFindingsPerPage} more ${category} findings*`
      );
      sections.push('');
    }
  }

  return sections.join('\n');
}

function generateFindingsByPage(
  findings: Finding[],
  opts: MarkdownReportOptions
): string {
  const sections: string[] = [];
  const grouped = groupByPage(findings);

  for (const [pageUrl, pageFindings] of grouped) {
    sections.push(`### 📄 ${pageUrl} (${pageFindings.length} issues)`);
    sections.push('');

    // Sort by severity within page
    const sorted = pageFindings.sort((a, b) => {
      const order: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
      return order[a.severity] - order[b.severity];
    });

    for (const finding of sorted.slice(0, opts.maxFindingsPerPage)) {
      sections.push(formatFinding(finding, opts, false)); // Don't repeat URL
      sections.push('');
    }

    if (pageFindings.length > opts.maxFindingsPerPage) {
      sections.push(`*... and ${pageFindings.length - opts.maxFindingsPerPage} more findings*`);
      sections.push('');
    }
  }

  return sections.join('\n');
}

function formatFinding(
  finding: Finding,
  opts: MarkdownReportOptions,
  includeUrl = true
): string {
  const lines: string[] = [];

  // Title with severity badge
  lines.push(`#### ${getSeverityEmoji(finding.severity)} ${finding.title}`);
  lines.push('');

  // Metadata
  lines.push(`- **ID:** \`${finding.id.substring(0, 50)}\``);
  lines.push(`- **Category:** ${finding.category}`);
  lines.push(`- **Confidence:** ${finding.confidence}`);
  lines.push(`- **Viewport:** ${finding.viewport}`);
  if (includeUrl) {
    lines.push(`- **URL:** ${finding.pageUrl}`);
  }
  if (finding.wcag) {
    lines.push(
      `- **WCAG:** ${finding.wcag.successCriteria.join(', ')} (${finding.wcag.version} ${finding.wcag.level})`
    );
  }
  if (finding.tool) {
    lines.push(`- **Tool:** ${finding.tool}${finding.ruleId ? ` (${finding.ruleId})` : ''}`);
  }
  lines.push('');

  // Description
  lines.push('**Description:**');
  lines.push('');
  lines.push(finding.description);
  lines.push('');

  // Steps to reproduce
  if (finding.stepsToReproduce.length > 0) {
    lines.push('**Steps to Reproduce:**');
    lines.push('');
    finding.stepsToReproduce.forEach((step, i) => {
      lines.push(`${i + 1}. ${step}`);
    });
    lines.push('');
  }

  // Expected vs Actual
  lines.push('**Expected:**');
  lines.push(`> ${finding.expected}`);
  lines.push('');
  lines.push('**Actual:**');
  lines.push(`> ${finding.actual}`);
  lines.push('');

  // Evidence
  if (opts.includeEvidence && finding.evidence.selectors.length > 0) {
    lines.push('**Selectors:**');
    lines.push('```css');
    lines.push(finding.evidence.selectors.join('\n'));
    lines.push('```');
    lines.push('');

    if (finding.evidence.domSnippet) {
      lines.push('<details>');
      lines.push('<summary>DOM Snippet</summary>');
      lines.push('');
      lines.push('```html');
      lines.push(finding.evidence.domSnippet);
      lines.push('```');
      lines.push('</details>');
      lines.push('');
    }
  }

  // Screenshot
  if (opts.includeScreenshots && finding.evidence.screenshotPath) {
    lines.push(`![Screenshot](${finding.evidence.screenshotPath})`);
    lines.push('');
  }

  // Suggested fix
  if (finding.suggestedFix) {
    lines.push('**Suggested Fix:**');
    lines.push('');
    lines.push(`> ${finding.suggestedFix}`);
    lines.push('');
  }

  // References
  if (finding.references && finding.references.length > 0) {
    lines.push('**References:**');
    for (const ref of finding.references) {
      lines.push(`- ${ref}`);
    }
    lines.push('');
  }

  // Affected pages (for clustered findings)
  if (finding.affectedPages && finding.affectedPages.length > 1) {
    lines.push(`**Also found on ${finding.affectedPages.length} pages:**`);
    lines.push('');
    for (const page of finding.affectedPages.slice(0, 5)) {
      lines.push(`- ${page}`);
    }
    if (finding.affectedPages.length > 5) {
      lines.push(`- ... and ${finding.affectedPages.length - 5} more pages`);
    }
    lines.push('');
  }

  lines.push('---');

  return lines.join('\n');
}

function getSeverityEmoji(severity: Severity): string {
  const emojis: Record<Severity, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  };
  return emojis[severity] || '⚪';
}

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
